apiVersion: apps/v1
kind: Deployment
metadata:
name: zomato
namespace: staging
spec:
replicas: 2
selector:
matchLabels:
app: zomato
template:
metadata:
labels:
app: zomato
spec:
containers:
- name: zomato
image: IMAGE_PLACEHOLDER
imagePullPolicy: Always
ports:
- containerPort: 3000
